### ISSUE TITLE
actions-rs is unmaintained, will stop working soon

### ISSUE THREAD

**Issue by HEnquist** [ejmahler/RustFFT#100]
The GitHub actions use actions-rs. This is unmaintained and will stop working once node 12 support is removed. 

I have started updating my projects and it's quite easy. I'll do the same here and submit a PR soon (if nobody beats me to it). Opening this issue to try to not forget to actually do it..

**Comment by HEnquist** [comment]
https://github.com/ejmahler/RustFFT/pull/101

**Comment by ejmahler** [comment]
Merged, thanks for updating it
