### ISSUE TITLE
output multiplied by n when doing fft forward then inverse of length n

### ISSUE THREAD

**Issue by epita-whatever** [ejmahler/RustFFT#103]
Hi, 
I've been messing around with the library to familiar myself with it. I wanted to test how precise it was so I did a fft forward then an inverse (both of length n) on the result and compared it to the initial input. However I find that the result correspond to the initial input with a factor of n. I've been looking in the library and did some research but I just can't find a reason for it to that.

Is there something I'm missing ? Or is it a bug issue ?

**Comment by WalterSmuts** [comment]
https://docs.rs/rustfft/latest/rustfft/#normalization

**Comment by epita-whatever** [comment]
How did I missed it ... I'm so sorry and thank you.

**Comment by WalterSmuts** [comment]
Perhaps we need to draw more attention to it in the docs? Have it earlier and surrounded by "⚠️" or "🚨" characters?

**Comment by epita-whatever** [comment]
It might help but I think the issue is just me being an idiot.

**Comment by HEnquist** [comment]
> Perhaps we need to draw more attention to it in the docs? Have it earlier and surrounded by "⚠️" or "🚨" characters?

Yeah there seems to be some confusion about this. It would probably be a good thing to make the normalization section more visible. Maybe a link from the "Usage" section? Or moving the whole Normalization up before cargo features
