### ISSUE TITLE
Release RustFFT v6.2.0

### ISSUE THREAD

**Issue by pr1metine** [ejmahler/RustFFT#127]
Hi all,
hope y'all have been doing well.

Lately, I've been able to convince my co-workers at work to use Rust for our next project. It compiles to WebAssembly and would depend on RustFFT. Last year, I implemented RustFFT's WASM SIMD support. WASM SIMD would probably accelerate our project substantially.

Is it possible for us to push a new release containing this feature?

**Comment by ejmahler** [comment]
https://crates.io/crates/rustfft/6.2.0

Apologies for the delay. Thank you very much for your hard work getting WASM support into the library!

**Comment by ejmahler** [comment]
and https://users.rust-lang.org/t/release-rustfft-6-2-now-with-support-for-wasm-simd-acceleration/105675
