### ISSUE TITLE
5.0 release

### ISSUE THREAD

**Issue by ejmahler** [ejmahler/RustFFT#32]
Things that need to happen before a 5.0 release

- [x] Upgrade guide from 4.0 to 5.0, since this release has nontrivial breaking changes
- [x] Update readme to have AVX performance tips, correct example, etc
- [x] Feature flag to disable AVX? This would improve compile times for users who know their target CPU doesn't support avx
- [x] Determine MSRV
- [x] Document MSRV update policy (Basically, copy tokio 1.0's policy of requring that a version of rustc be out for 6 months before depending on it)
- [x] Document policy on future major releases (No breaking changes for 3 years, EXCEPT for if we need to upgrade our version of num-traits/num-complex)
- [x] Get ARM CI going
- [x] Hide the FftPlanner enum from the public API by wrapping it in a wrapper struct
- [x] Add MSRV to CI

This release will have a lot of breaking changes, and I'd like to avoid making any for a long time afterwards, so if we have any other breaking changes, we need to get them in soon.

**Comment by HEnquist** [comment]
I have thought a little and have two things that maybe should be on the list:
- CI for more platforms, especially something without avx like arm (I can set this up)
- Prepare so other instruction sets can be added without breaking changes. I'm thinking sse and neon. Neon seems to lack a lot of intrinsics so might be some way off, but sse could be started now. I haven't looked carefully at this, could be a non-issue.

**Comment by ejmahler** [comment]
That's a good point about adding new SIMD sets. I changed FftPlanner to be a public enum, meaning adding new entries to that enum would be a breaking change. I'll have to make it private and wrap it in a struct.

Once that happens, I think we're ready to go WRT adding new instruction sets like SSE - we just need to add new entries to the FftPlanner enum, and update FftPlanner's constructor to attempt to create an instance of FftPlannerNeon or whatever, the same way it does AVX.

My plan right now is to write algorithms from the ground up for each instruction set. Eventually, I may abstract an instruction set agnostic section of the code, and I bet that for example the MixedRadix8xn etc structs can be written entirely in simd-agnostic code. But first, I'd like to get a few independently-implemented instruction sets going so I can see what sorts of patterns develop.

As for testing, I'm totally on board with getting arm-based CI. I'm also very nervous about the fact that all of the AVX unit tests simply crash if they're run on a x86_64 platform without AVX. It probably isn't a problem now, since virtually everyone running rustfft's unit tests on x86_64 will have AVX. But if we add an avx-512 module, those unit tests definitely should not crash. It would be nice if rust's test runner had a way to conditionally ignore tests.

**Comment by HEnquist** [comment]
Which guide is the first point refering to?

**Comment by ejmahler** [comment]
I intend to write a guide for specifically how tro u[grade from 4.0 to 5.0.

**Comment by HEnquist** [comment]
Ah I see, write a new upgrade guide. That is definitely useful. I read it as upgrading an existing guide.

**Comment by ejmahler** [comment]
First draft of upgrade guide is finished: https://github.com/ejmahler/RustFFT/blob/master/UpgradeGuide4to5.md

I also made a last minute breaking change to cut down the number of methods in the Fft trait and reorganize them.

I'll do one more pass over the documentation tomorrow and publish 5.0 if everything looks good.

**Comment by ejmahler** [comment]
RustFFT 5.0 has been released.

**Comment by HEnquist** [comment]
Great!! Then it's time to start updating everything else to use it :)
