### ISSUE TITLE
Using &mut [MaybeUnInit<Complex<T>>] for output and scratch

### ISSUE THREAD

**Issue by RamType0** [ejmahler/RustFFT#79]
Because the initial value of these would not affect the result , we could use `&mut [MaybeUnInit<Complex<T>>]` instead of `&mut [Complex<T>]`.

**Comment by ejmahler** [comment]
I think I have to say no to this, unfortunately. 

Forcing all users to do this would be a large ergonomics burden on users, and adding it as an alternative API would require a very large amount of boilerplate that would be too large to maintain and document.

I appreciate the suggestion though!

**Comment by WalterSmuts** [comment]
@RamType0, what was your motivation for suggesting this?

**Comment by RamType0** [comment]
> @RamType0, what was your motivation for suggesting this?

Zero initializing `output` and `scratch` before we pass them to this function is unnecessary cost.

I think using `&mut [MaybeUnInit<Complex<T>>]` is better for `scratch` at least.
