### ISSUE TITLE
Frequency Components for discretized sin wave

### ISSUE THREAD

**Issue by SallySoul** [ejmahler/RustFFT#83]
Hey! Thanks for making this high quality library.

This is not a bug report. However, I'm confused about some output I'm seeing and I'm not sure where else to go for help. I completely understand if you close this as off topic or whatever.

What I'm seeing is that running FFT on a discretized sin wave over [0, 2pi) has non-zero frequency components for all frequencies. What I would expect to see is just one non-zero frequency component.

Consider the following example:
```
use rustfft::{FftPlanner, num_complex::Complex64};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let step_count = 8;

    // x = 0 and x = 2*pi are the same, so exclude x = 2 * pi by adding one extra step
    let step_size = 2.0 * std::f64::consts::PI / (step_count as f64 + 1.0);
    let x_values: Vec<f64> = (0..step_count)
        .map(|i| i as f64 * step_size)
        .collect();
    let y_values: Vec<f64> = x_values.iter()
        .map(|x| x.sin())
        .collect();

    let mut complex_y_values: Vec<Complex64> = y_values.iter()
        .map(|y| Complex64::new(*y, 0.0))
        .collect();
    let mut planner = FftPlanner::new();
    let fft = planner.plan_fft_forward(step_count);
    fft.process(&mut complex_y_values);
    println!("Forward FFT Results");
    for (i, c) in complex_y_values.iter().enumerate() {
        println!("i: {}, c: {}", i, c);
    }

    let ifft = planner.plan_fft_inverse(step_count);
    ifft.process(&mut complex_y_values);
    println!("Inverse FFT Results");
    for (i, c) in complex_y_values.iter().enumerate() {
        println!("i: {}, normalized real: {}", i, c.re / step_count as f64);
    }
    Ok(())
}
```

Which prints the following:
```
Forward FFT Results
i: 0, c: 0.6427876096865397+0i
i: 1, c: -0.9543925790214637-3.855934073132479i
i: 2, c: 0.22323779409789923-0.41954981558864i
i: 3, c: 0.2703522923701259-0.15426775953918614i
i: 4, c: 0.27881737542033735+0i
i: 5, c: 0.2703522923701259+0.15426775953918614i
i: 6, c: 0.22323779409789923+0.41954981558864i
i: 7, c: -0.9543925790214637+3.855934073132479i
Inverse FFT Results
i: 0, normalized real: 0
i: 1, normalized real: 0.6427876096865394
i: 2, normalized real: 0.9848077530122081
i: 3, normalized real: 0.8660254037844388
i: 4, normalized real: 0.3420201433256689
i: 5, normalized real: -0.34202014332566877
i: 6, normalized real: -0.8660254037844384
i: 7, normalized real: -0.9848077530122084
```
So I have successfully recovered the inputs values with fft -> inverse fft. However, I would expect only the second frequency to have value with the other frequency components taking on zero or approximately zero values. That is the result I see when running a comparable example through Matlab's fft functionality, and intuitively it makes sense to me.

You wouldn't happen to see where my confusion is coming from would you?

**Comment by HEnquist** [comment]
I believe the problem is this:
`// x = 0 and x = 2*pi are the same, so exclude x = 2 * pi by adding one extra step`
Your x-values will be the eight numbers zero to seven, so 2*pi won't be included anyway. Now you exclude the value before that too. Try without that "+ 1.0" and it should be fine.

**Comment by SallySoul** [comment]
🤦 ah that fixed things!

Thanks so much for your time!
