### ISSUE TITLE
State of Project

### ISSUE THREAD

**Issue by ferjif** [ejmahler/RustFFT#88]
Is this project still actively maintained?

because the last commit is from October 2021. Hope not. I really like this library and plan on using it more and more.

**Comment by HEnquist** [comment]
It's actively maintained yes. The low rate of commits is just because it's quite mature by now. Bugs are rare, but fixed quickly when found. The next larger change will be when neon support gets finalized, hopefully very soon.

**Comment by ejmahler** [comment]
Repo owner here - I still keep up with issues and review PRs.

I don't have much time to implement smaller feature requests right now, but I would happy give feedback and accept PRs for them. Other than that, there's not much to do. As @HEnquist said, I consider this library relatively mature, so there just aren't many changes to be made.
