### ISSUE TITLE
is_aarch64_feature_detected!("neon")

### ISSUE THREAD

**Issue by lukaz-vaultree-com** [ejmahler/RustFFT#91]
`if is_aarch64_feature_detected!("neon") {`

does not compile, I had to change it to

`if std::arch::is_aarch64_feature_detected!("neon") {`

:)

**Comment by lukaz-vaultree-com** [comment]
macOS Apple Silicon

**Comment by HEnquist** [comment]
Please see https://github.com/ejmahler/RustFFT/pull/84
