### ISSUE TITLE
DWT support

### ISSUE THREAD

**Issue by lzunsec** [ejmahler/RustFFT#92]
Hello, is there interest for a PR with DWT support? Multiplying polynomials mod x^n+1 is very important for lattice cryptography. Is this lib suitable for it? Since this lib uses floating point I don't know if it will work

**Comment by ejmahler** [comment]
I've looked into DWT before and I find it interesting. I suspect it would be sort of mission creep for this crate to implement it though. I'm going to say no for now, in the interest of keeping this crate tightly focused on its initial goals.
