### ISSUE TITLE
Question: how to get frequency and phase from complex numbers

### ISSUE THREAD

**Issue by beckend** [ejmahler/RustFFT#99]
I was wondering how I get that, are there recommended crates to convert these numbers?

**Comment by HEnquist** [comment]
This may be helpful: https://www.mathworks.com/help/matlab/ref/fft.html

That shows how to get the frequency and amplitude. Phase is more difficult. In principle it's just the angle of the complex numbers, but interpreting the number to something useful tends to get tricky. What do you want to achieve?

**Comment by beckend** [comment]
I have microphone audio samples of amplitudes in f32, Ineed continuous frequency, phase, amplitude data. I do not quite understand what code to write to get such data using rustfft.

**Comment by HEnquist** [comment]
Rustfft does a standard fft, it gives you the same result as pretty much any other fft out there. I would suggest prototyping in something more interactive until you know exactly what to do. Python (with numpy), Matlab or Octave for example. They have fft functions that give the same result, and you can easily plot the data as you work on the algorithms.

**Comment by beckend** [comment]
Ok thanks
